Suggesting using addEventListener once option in docs
animate-css/animate.css pull request #1096
Opened 2020-08-28 01:39 UTC by Gibolt

Adding `{once : true}` to `node.addEventListener` causes the event trigger to be removed after first use. This built-in method cleans up the requirement to remove event within event handler.

2020-08-30 10:31 UTC, WarenGonzaga commented
Awesome! Thanks for improving the code... @eltonmesquita kindly review it.

2020-09-01 12:52 UTC, eltonmesquita requested changes

2020-09-01 12:52 UTC, eltonmesquita commented on docsSource/sections/04-javascript.md
> +    handleAnimationEnd = () => {
Please revert to the regular `function` declaration.

2020-09-07 08:55 UTC, eltonmesquita commented
Any news on this @Gibolt ?

2020-09-17 18:16 UTC, merged

2020-09-17 18:17 UTC, eltonmesquita commented
I pulled this, solved the problem and pushed into main. Thanks for contributing.